name: Release CI
on:
  push:
    branches:
      - master
      - next
      - beta
      - alpha
      - pre/rc
      - 1.x
      - 2.x

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: c-hive/gha-yarn-cache@v1

      - name: install
        run: yarn

      - name: release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
